version: '3.7'
services:
        web:
            build: . 
            environment:
                          -REDIS_HOST=redis
            port:
                          - "3700:3700"
            depends_on:
                          -redis
        redis:
            image: redis
